-- ============================================================
-- Canlı şemayı dışa aktarma (yalnızca yapı; VERİ ve SIR YOK)
--
-- Neden: ARC'ın tablolarının ve fonksiyonlarının çoğu depoda değil,
-- yalnızca canlı veritabanında. Depo veritabanını yeniden kuramıyor,
-- denetim fonksiyon gövdelerini göremiyor.
--
-- Kullanım: Supabase → SQL Editor'de bu dosyanın tamamını çalıştırın.
-- Tek satır, tek sütun (ddl) döner. Hücreyi kopyalayıp
-- supabase/schema/canli-sema.sql dosyasına yapıştırın.
--
-- Salt okunurdur: hiçbir şeyi değiştirmez. pg_dump'ın yerini tutmaz
-- (uzantılar, tablo yetkileri, domain ve bileşik tipler, private şemasındaki
-- tablolar yok) ama enum
-- tiplerini, sekansları, tabloları, kimlik sütunlarını, varsayılanları,
-- kısıtları, indeksleri, RLS'i, politikaları, görünümleri, fonksiyonları
-- (public ve private), fonksiyon yetkilerini ve tetikleyicileri kapsar.
-- ============================================================
with
tablolar as (
  select c.oid, c.relname,
         c.relrowsecurity as rls
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r'
),
tablo_ddl as (
  select t.relname as ad, 10 as sira,
         format(E'create table if not exists public.%I (\n%s\n);',
           t.relname,
           string_agg(
             format('  %I %s%s%s',
               a.attname,
               format_type(a.atttypid, a.atttypmod),
               case a.attidentity
                 when 'a' then ' generated always as identity'
                 when 'd' then ' generated by default as identity'
                 else '' end,
               case when a.attnotnull then ' not null' else '' end),
             E',\n' order by a.attnum)) as ddl
  from tablolar t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  group by t.relname
),
-- Varsayılanlar tablodan ayrı ve fonksiyonlardan SONRA: bir varsayılan
-- public'teki bir fonksiyonu çağırabilir.
varsayilan_ddl as (
  select t.relname as ad, 17 as sira,
         format('alter table public.%I alter column %I set default %s;',
           t.relname, a.attname, pg_get_expr(d.adbin, d.adrelid)) as ddl
  from tablolar t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  join pg_attrdef d on d.adrelid = t.oid and d.adnum = a.attnum
  where a.attidentity = '' and a.attgenerated = ''
),
tip_ddl as (
  select ty.typname as ad, 3 as sira,
         format('do $t$ begin create type public.%I as enum (%s); exception when duplicate_object then null; end $t$;',
           ty.typname,
           (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
              from pg_enum e where e.enumtypid = ty.oid)) as ddl
  from pg_type ty
  join pg_namespace n on n.oid = ty.typnamespace
  where n.nspname = 'public' and ty.typtype = 'e'
),
sekans_ddl as (
  select c.relname as ad, 5 as sira, format('create sequence if not exists public.%I;', c.relname) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'S'
    and not exists (select 1 from pg_depend dep where dep.objid = c.oid and dep.deptype = 'i')
),
kisit_ddl as (
  select t.relname as ad,
         case when con.contype = 'f' then 30 else 20 end as sira,
         format('alter table public.%I add constraint %I %s;', t.relname, con.conname, pg_get_constraintdef(con.oid)) as ddl
  from tablolar t
  join pg_constraint con on con.conrelid = t.oid
),
-- İndeksler yabancı anahtarlardan (30) ÖNCE: bir yabancı anahtar benzersiz
-- indekse dayanabiliyor (billing_invoices); sonra gelirse döküm kurulamıyor.
indeks_ddl as (
  select t.relname as ad, 25 as sira, pg_get_indexdef(i.indexrelid) || ';' as ddl
  from tablolar t
  join pg_index i on i.indrelid = t.oid
  -- Yalnızca pk/unique/exclusion kısıtının KENDİ indeksi atlanır. Yabancı
  -- anahtar da dayandığı indeksi conindid'de gösteriyor; eski filtre bu yüzden
  -- billing_invoices_id_org_uidx gibi bağımsız benzersiz indeksleri düşürüyor,
  -- döküm kurulamıyordu.
  where not exists (select 1 from pg_constraint c where c.conindid = i.indexrelid and c.contype in ('p', 'u', 'x'))
),
rls_ddl as (
  select relname as ad, 50 as sira, format('alter table public.%I enable row level security;', relname) as ddl
  from tablolar where rls
),
politika_ddl as (
  select p.tablename as ad, 60 as sira,
         format(E'create policy %I on public.%I as %s for %s to %s%s%s;',
           p.policyname, p.tablename, p.permissive, p.cmd,
           array_to_string(p.roles, ', '),
           case when p.qual is not null then E'\n  using (' || p.qual || ')' else '' end,
           case when p.with_check is not null then E'\n  with check (' || p.with_check || ')' else '' end) as ddl
  from pg_policies p
  where p.schemaname = 'public'
),
gorunum_ddl as (
  select c.relname as ad, 45 as sira,
         format(E'create or replace view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true)) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'
),
fonksiyon_ddl as (
  select n.nspname || '.' || p.proname as ad, 15 as sira, pg_get_functiondef(p.oid) || ';' as ddl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname in ('public', 'private') and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
),
yetki_ddl as (
  select n.nspname || '.' || p.proname as ad, 85 as sira,
         format('revoke all on function %I.%I(%s) from public;', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid))
         || coalesce(E'\n' || string_agg(
              format('grant execute on function %I.%I(%s) to %s;',
                n.nspname, p.proname, pg_get_function_identity_arguments(p.oid),
                case when acl.grantee = 0 then 'public' else quote_ident(r.rolname) end),
              E'\n'), '') as ddl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  left join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) acl on acl.privilege_type = 'EXECUTE'
  left join pg_roles r on r.oid = acl.grantee
  where n.nspname in ('public', 'private') and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
    and (acl.grantee is null or acl.grantee <> p.proowner)
  group by p.oid, n.nspname, p.proname
),
tetikleyici_ddl as (
  select c.relname as ad, 90 as sira, pg_get_triggerdef(tg.oid) || ';' as ddl
  from pg_trigger tg
  join pg_class c on c.oid = tg.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not tg.tgisinternal
),
hepsi as (
  select * from tip_ddl union all select * from sekans_ddl union all
  select * from varsayilan_ddl union all
  select * from tablo_ddl union all select * from kisit_ddl union all
  select * from indeks_ddl union all select * from rls_ddl union all
  select * from politika_ddl union all select * from gorunum_ddl union all
  select * from fonksiyon_ddl union all select * from yetki_ddl union all
  select * from tetikleyici_ddl
)
select E'-- Canlı şema dışa aktarımı: ' || now()::date || E'\n-- scripts/sema-disa-aktar.sql ile üretildi. Elle düzenlemeyin.\n'
       || E'-- Sıra: tipler, sekanslar, tablolar, fonksiyonlar, varsayılanlar,\n'
       || E'-- kısıtlar, yabancı anahtarlar, indeksler, görünümler, RLS, politikalar,\n'
       || E'-- yetkiler, tetikleyiciler. Fonksiyon gövdeleri tablolar tamamlanmadan\n'
       || E'-- denetlenmesin diye:\n'
       || E'set check_function_bodies = false;\n'
       || E'-- Politikalar ve tetikleyiciler private şemasındaki fonksiyonlara dayanıyor.\n'
       || E'create schema if not exists private;\n\n'
       || string_agg(ddl, E'\n\n' order by sira, ad, ddl) as ddl
from hepsi;
